### ISSUE TITLE
Crash to Launcher when using LineageOS/microG/Yalp

### ISSUE THREAD

**Issue by JanKrAppel** [NiciDieNase/chaosflix#30]
The newest Version just crashes to the launcher on a device running LineageOS with microG and installed via Yalp store. No error message or anything, but if someone explains how to geht them, I'll gladly post logs or otherwise help with debugging.

**Comment by TWuerdemann** [comment]
Maybe a similar issue. Also crashes on Honor 9 with official Android Pie (9) Beta version.

**Comment by NiciDieNase** [comment]
I'm sorry, but since I don't have access to devices with your conficurations, I can't try to reproduce the crashes myself.
In the crash reports I get from Google Play I see a crash related to the database-migration.
If your crashes appear after upgrading from a previous version deleting all app data might fix the crash, but you would use all user specific data (bookmarks, playback progress, etc.)

**Comment by TWuerdemann** [comment]
Okay. After an uninstall/reinstall the App kept crashing.
But deleting all data in the App setting did the trick. So I can confirm it is working now.

**Comment by JanKrAppel** [comment]
The crash appeared first when I tried upgrading. I tried clearing app data AS well AS uninstalling and reinstalling the app without success. Sorry, should've mentioned that in the first post. Is there any debug data I can provide to help?


Am 29. Dezember 2018 02:02:31 MEZ schrieb Felix <notifications@github.com>:
>I'm sorry, but since I don't have access to devices with your
>conficurations, I can't try to reproduce the crashes myself.
>In the crash reports I get from Google Play I see a crash related to
>the database-migration.
>If your crashes appear after upgrading from a previous version deleting
>all app data might fix the crash, but you would use all user specific
>data (bookmarks, playback progress, etc.)

-- 
XMPP: jan@janappel.info
GPG: 5554E188 @ http://pool.sks-keyservers.net/

**Comment by NiciDieNase** [comment]
@JanKrAppel Could be related to your LineageOS/microG setup.
If your are at 35c3 we could meet up and investigate the issue further.

**Comment by deraffe** [comment]
Here's a traceback from my LineageOS 14.1 (Android 7.1.2) with microG 0.2.6 and Xposed 89.
Edit: Found more relevant logs a couple of lines down

```
1725 25782 I ActivityManager: START u0 {cmp=de.nicidienase.chaosflix/.touch.browse.BrowseActivity} from uid 10254 on display 0
3543  3543 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
3543  3543 I art     :   at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
3543  3543 I art     :   at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
3543  3543 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
3543  3543 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
3543  3543 I art     :   at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
3543  3543 I art     :   at android.databinding.ViewDataBinding android.databinding.DataBindingUtil.setContentView(android.app.Activity, int, android.databinding.DataBindingComponent) (DataBindingUtil.java:303)
3543  3543 I art     :   at android.databinding.ViewDataBinding android.databinding.DataBindingUtil.setContentView(android.app.Activity, int) (DataBindingUtil.java:284)
3543  3543 I art     :   at void de.nicidienase.chaosflix.touch.browse.BrowseActivity.onCreate(android.os.Bundle) (BrowseActivity.kt:66)
3543  3543 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
3543  3543 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
3543  3543 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
3543  3543 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
3543  3543 I art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
3543  3543 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
3543  3543 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
3543  3543 I art     :   at void android.os.Looper.loop() (Looper.java:154)
3543  3543 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
3543  3543 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
3543  3543 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
3543  3543 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
3543  3543 I art     :   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:107)
3543  3543 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/de.nicidienase.chaosflix-1/base.apk"],nativeLibraryDirectories=[/data/app/de.nicidienase.chaosflix-1/lib/arm64, /system/lib64, /vendor/lib64]]
3543  3543 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
3543  3543 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
3543  3543 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
3543  3543 I art     :   at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
3543  3543 I art     :   at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
3543  3543 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
3543  3543 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
3543  3543 I art     :   at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
3543  3543 I art     :   at android.databinding.ViewDataBinding android.databinding.DataBindingUtil.setContentView(android.app.Activity, int, android.databinding.DataBindingComponent) (DataBindingUtil.java:303)
3543  3543 I art     :   at android.databinding.ViewDataBinding android.databinding.DataBindingUtil.setContentView(android.app.Activity, int) (DataBindingUtil.java:284)
3543  3543 I art     :   at void de.nicidienase.chaosflix.touch.browse.BrowseActivity.onCreate(android.os.Bundle) (BrowseActivity.kt:66)
3543  3543 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
3543  3543 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
3543  3543 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
3543  3543 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
3543  3543 I art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
3543  3543 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
3543  3543 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
3543  3543 I art     :   at void android.os.Looper.loop() (Looper.java:154)
3543  3543 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
3543  3543 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
3543  3543 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
3543  3543 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
3543  3543 I art     :   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:107)
3543  3543 I art     : 
3543  3548 I art     : Do partial code cache collection, code=15KB, data=26KB
3543  3548 I art     : After code cache collection, code=15KB, data=26KB
3543  3548 I art     : Increasing code cache capacity to 128KB

3543  3543 D AndroidRuntime: Shutting down VM
3543  3543 E AndroidRuntime: FATAL EXCEPTION: main
3543  3543 E AndroidRuntime: Process: de.nicidienase.chaosflix, PID: 3543
3543  3543 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.nicidienase.chaosflix/de.nicidienase.chaosflix.touch.browse.BrowseActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.cast.framework.zzp com.google.android.gms.cast.framework.zzj.zzac()' on a null object reference
3543  3543 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
3543  3543 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
3543  3543 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
3543  3543 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
3543  3543 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
3543  3543 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
3543  3543 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
3543  3543 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
3543  3543 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
3543  3543 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
3543  3543 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
3543  3543 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.cast.framework.zzp com.google.android.gms.cast.framework.zzj.zzac()' on a null object reference
3543  3543 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
3543  3543 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
3543  3543 E AndroidRuntime:        at pl.droidsonroids.casty.Casty.<init>(Casty.java:90)
3543  3543 E AndroidRuntime:        at pl.droidsonroids.casty.Casty.create(Casty.java:73)
3543  3543 E AndroidRuntime:        at de.nicidienase.chaosflix.touch.browse.BrowseActivity.onCreate(BrowseActivity.kt:68)
3543  3543 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6684)
3543  3543 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
3543  3543 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
3543  3543 E AndroidRuntime:        ... 10 more
1725  2922 W ActivityManager:   Force finishing activity de.nicidienase.chaosflix/.touch.browse.BrowseActivity
1725  3568 W DropBoxManagerService: Dropping: data_app_crash (2039 > 0 bytes)
1725  1768 W ActivityManager: Activity pause timeout for ActivityRecord{545d1ba u0 de.nicidienase.chaosflix/.touch.browse.BrowseActivity t7726 f}
1725  1768 I ActivityManager: Killing 3196:com.android.externalstorage/u0a13 (adj 906): empty #17
1725 25781 D ActivityManager: cleanUpApplicationRecord -- 3196
```

**Comment by JanKrAppel** [comment]
I also managed to dig up a traceback, it looks like the same issue on first glance:

`01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: FATAL EXCEPTION: main
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: Process: de.nicidienase.chaosflix, PID: 5438
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.nicidienase.chaosflix/de.nicidienase.chaosflix.touch.browse.BrowseActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.cast.framework.zzp com.google.android.gms.cast.framework.zzj.zzac()' on a null object reference
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.cast.framework.zzp com.google.android.gms.cast.framework.zzj.zzac()' on a null object reference
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:39)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:6)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at pl.droidsonroids.casty.Casty.<init>(Casty.java:90)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at pl.droidsonroids.casty.Casty.create(Casty.java:73)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at de.nicidienase.chaosflix.touch.browse.BrowseActivity.onCreate(BrowseActivity.kt:68)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
01-06 09:34:03.246 10102  5438  5438 E AndroidRuntime: 	... 9 more
`

**Comment by NiciDieNase** [comment]
`Attempt to invoke interface method 'com.google.android.gms.cast.framework.zzp`

I assume microG does not support Chromecast?

I want to add a additional build-flavor without play-services for publishing the app in F-Droid, this should solve the issue.
Until then, you propably can use version [0.3](https://github.com/NiciDieNase/chaosflix/releases/tag/0.3.0) which does not yet have chromecast support.

**Comment by deraffe** [comment]
Apparently not. I found microg/android_packages_apps_GmsCore#636 which talks about a similar problem.

But I can confirm that 0.3 works flawlessly.

**Comment by JanKrAppel** [comment]
0.3 works for me as well. Having a F-Droid build flavor would be awesome nevertheless :-)

Thanks for your work and help!

Am 13. Januar 2019 18:27:26 MEZ schrieb Felix <notifications@github.com>:
>`Attempt to invoke interface method
>'com.google.android.gms.cast.framework.zzp`
>
>I assume microG does not support Chromecast?
>
>I want to add a additional build-flavor without play-services for
>publishing the app in F-Droid, this should solve the issue.
>Until then, you propably can use version
>[0.3](https://github.com/NiciDieNase/chaosflix/releases/tag/0.3.0)
>which does not yet have chromecast support.

-- 
XMPP: jan@janappel.info
GPG: 5554E188 @ http://pool.sks-keyservers.net/

**Comment by dueringa** [comment]
Self-build version 0.5 touch-dev-free-debug.apk doesn't crash for me on launch (LineageOS 7.1.2, microG, no Google Play Store)
